name: City_Guardian
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3
  geocoding: ^2.1.0
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0 # ✅ Re-enabled Google Maps
  geolocator: ^11.0.0
  permission_handler: ^11.0.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  google_sign_in: ^6.1.0
  http: ^1.1.0
  flutter_animate: ^4.5.2
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/pothole1.jpg
    - assets/pothole2.jpg
    - assets/pothole3.jpg
    - assets/pothole4.jpg
    - assets/deepak.jpeg
